# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 250fd02144081783285a721e34ba122559767c06f8352c324a09c8fa47738ad60834755a41a4a148809431675d9422b5ccbca17cb0c8bc0d45e31ca85089f030

test:
  secret_key_base: 7b5ddca5db468a44e58c7ff0a48ae397875b32db635062bea6736510571c7cdef4936c3757a5a51633b32434177c10bec95e5dea58d9153e6e44064055aaf5c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
