  defaults: &defaults
    ACTIVE_STATUS : ["引合","提案前","提案済","提案結果待ち","受注"]
    emails:
      address: 'test@abc.co.jp'
      for_name: 'test'

    notice_info:
      create_comment:
        title: '新規にコメントを登録しました。'
        contents: 'コメントが登録されました。'
        anken_info: '対象の案件はXXXです。'
        url: 'http://172.19.80.225:3000'
      create_anken:
        title: '案件が作成されました。'
        contents: '新規に案件が登録されました。'
        anken_info: '対象の案件はXXXです。'
        url: 'http://172.19.80.225:3000'

  development:
    <<: *defaults

  test:
    <<: *defaults

  production:
    <<: *defaults
